apiVersion: v1
kind: Service
metadata:
  name: particle41-service
spec:
  type: NodePort
  selector:
    app: particle41-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
