name: Particle41 CICD
on:
  push:
    branches:
      - main
    paths:
      - "/app/**"
      - "/terraform/**"
  workflow_dispatch:
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
        working-directory: app
      - name: Test
        run: npm test
        working-directory: app
      - name: Audit
        run: npm audit --audit-level=low
        working-directory: app
      - name: Lint
        run: npm run lint
        working-directory: app
      - name: Build TypeScript
        run: npm run build
        working-directory: app
      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851717133722.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        working-directory: app
      - name: Configure Docker Buildx
        run: docker buildx create --use
        working-directory: app
      - name: Build and Push Docker Image to ECR
        working-directory: app
        run: |
          IMAGE_TAG=851717133722.dkr.ecr.us-east-1.amazonaws.com/particle41-ecr-dev:${{ github.sha }}
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAG --push .
